services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persons_db
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'